[(NOUN mqlpiM)][(PREFIX w)(VERB xwtkiM)][(PREPOSITION at)][(NOUN-DEF harviewqiM)][(ADJECTIVE-DEF hirwelmiM)][(PREFIX l)(NOUN-CONST rcwywt)][(NOUN dqwt)][(CM CM)][(VERB meriM)][(PREFIX b)(NOUN-CONST miC)][(NOUN limwN)][(PREFIX l)	(NOUN-CONST meK)][(NUMERAL 3)][(NOUN eywt)][(PREFIX b)(NOUN mqrr)][(DOT DOT)]
[(VERB mqlpiM)][(PREPOSITION at)][(NOUN-DEF harviewqiM)][(ADJECTIVE-DEF hrgiliM)][(CM CM)][(VERB mbeliM)][(PREPOSITION awtM)][(PREFIX b)	(NOUN-DEF miM)][(CM CM)][(NOUN miC)][(NOUN limwN)][(PREFIX w)(NOUN-CONST kP)][(NOUN qmx)][(ADJECTIVE mksiM)][(PREPOSITION at)][(VERB hsir)][(PREFIX b)(NOUN-CONST niir)][(NOUN prgmnv)][(PREFIX w)(NOUN mbeliM)][(PREPOSITION yl)][(NOUN ae)][(ADJECTIVE nmwkh)][(PREFIX k)][(DASH DASH)][(NUMERAL 40)][(NOUN dqwt)][(PREPOSITION yd)][(PREFIX l)(NOUN-CONST htrkkwt)][(NOUN-DEF harviewqiM)][(CM CM)][(VERB mqrriM)][(PREFIX w)(NOUN xwtkiM)][(PREFIX l)	(NOUN prwswt)][(ADJECTIVE dqwt)][(DOT DOT)]
[(NOUN plpliM)][(ADJECTIVE xwtkiM)][(PREFIX l)(NOUN-DEF qwbiwt)][(CM CM)][(VERB myrbbiM)][(PREPOSITION at)][(QUANTIFIER kl)][(NOUN-DEF hxwmriM)][(PREFIX b)(NOUN-DEF cncnt)][(PREFIX w)(VERB mnyriM)][(ADVERB hivb)][(PREFIX w)(VERB mgieiM)]
</paragraph>
[(NOUN rwvb)][(PREFIX l)(NOUN-CONST slv)][(NUMERAL 1)][(NOUN-CONST kP)][(NOUN dbe)][(PUNC PUNC)][(NUMERAL 4)][(NOUN-CONST kpwt)][(NOUN-CONST xwmC)][(NOUN-CONST eri)][(PUNC PUNC)][(NUMERAL 1/2)][(NOUN-CONST kws)][(NOUN emN)][(NOUN zit)][(PUNC PUNC)][(NUMERAL 1/2)][(NOUN-CONST kpit)][(NOUN mlx)][(DOT DOT)]
[(VERB myrbbiM)][(PREPOSITION yd)][(PREFIX e)(NOUN-DEF hdbe)][(VERB nms)][(DOT DOT)]
[(VERB mcpiM)][(PREPOSITION at)][(NOUN-CONST gbint)][(NOUN-DEF hyziM)][(VERB-INF bqmx)][(CM CM)][(NOUN bich)][(ADJECTIVE vrwph)][(CM CM)][(PREFIX w)	(ADVERB ewb)][(VERB qmx)][(CM CM)][(VERB mnixiM)][(PREPOSITION yl)][(NOUN ret)][(PREFIX w)(NOUN nwtniM)][(PREFIX l)	(NOUN-DEF cipwi)][(VERB-INF lhtibe)][(DOT DOT)]
[(VERB qwliM)][(PREPOSITION at)][(NOUN-CONST plxi)][(NOUN-DEF hags)][(PREFIX b)(NOUN-DEF gril)][(CONJUNCTION aw)][(PREFIX b)(NOUN mxbv)][(PREFIX m)(NOUN xwrct)][(PREPOSITION yd)][(PREFIX e)	(PRONOUN hwa)][(ADJECTIVE rK)][(DOT DOT)]
[(VERB mxmmiM)][(NOUN emN)][(PREFIX l)(NOUN vigwN)][(ADJECTIVE ymwq)][(CM CM)][(VERB mvgniM)][(PREPOSITION at)][(NOUN-CONST gbint)][(NOUN-DEF hyziM)][(PREPOSITION yd)][(PREFIX l)	(NOUN-CONST qblt)][(NOUN gwwN)][(ADJECTIVE zhwb)][(DOT DOT)]
[(VERB mrkibiM)][(PREPOSITION at)][(NOUN-DEF hslv)][(NOUN yliM)][(ADJECTIVE irwqiM)][(PUNC PUNC)][(PROPERNAME pilxi)][(NOUN tpwz)][(PUNC PUNC)][(NUMERAL 3)][(NOUN-CONST kpwt)][(NOUN-CONST rwvb)][(PROPERNAME dbe)][(CM CM)][(VERB myrbbiM)][(ADVERB bixd)][(PREFIX w)(NOUN msdriM)][(PREFIX b)	(NOUN-DEF clxt)][(DOT DOT)]
[(VERB msdriM)][(ADVERB msbib)][(PREPOSITION at)][(NOUN-CONST plxi)][(NOUN-DEF hags)][(PREFIX w)][(NOUN-CONST gbint)][(NOUN-DEF hyziM)][(ADJECTIVE-DEF hxmh)][(DOT DOT)]
</paragraph>
[(PREFIX b)(NOUN qyrh)][(ADJECTIVE gdwlh)][(VERB myrbbiM)][(PREFIX b)	(NOUN-CONST er)][(CM CM)][(NOUN bcl)][(CM CM)][(NOUN slri)][(CM CM)][(NOUN tpwxiM)][(PROPERNAME wpqaniM)][(DOT DOT)]
[(PREFIX b)(NOUN qyrh)][(ADJECTIVE qvnh)][(VERB myrbbiM)][(PREPOSITION at)][(NOUN-CONST xwmri)][(NOUN-DEF hrwvb)][(CM CM)][(PREFIX w)(VERB mwsipiM)][(PREFIX l)(NOUN-CONST tyrwbt)][(NOUN-DEF hber)][(PREFIX w)(NOUN-DEF hirqwt)][(DOT DOT)]
[(VERB msdriM)][(PREPOSITION at)][(PROPERNAME harwgwlh)][(CONJUNCTION aw)][(VERB hxsh)][(PREFIX b)(NOUN-CONST qyrt)][(NOUN hgeh)][(CM CM)][(PREFIX w)	(PREPOSITION at)][(NOUN-DEF hslv)][(PREPOSITION yl)][(PROPERNAME harwgwlh)][(DOT DOT)]
[(ADJECTIVE mgieiM)][(ADVERB mid)][(CM CM)][(CONJUNCTION aw)][(VERB ewmriM)][(PREFIX b)(NOUN mqrr)][(PREPOSITION yd)][(PREFIX l)(NOUN hgeh)][(DOT DOT)]
EOF
