[(VERB pwrsiM)][(PREPOSITION at)][(NOUN-DEF hxciliM)][(PREFIX l)(NOUN-POSSESSIVE awrkM)][(LRB LRB)][(NEGATION la)][(NOUN qwlpiM)][(RRB RRB)][(PREFIX l)	(NOUN prwswt)][(PREFIX b)	(NOUN-DEF ywbi)][(PREFIX k)][(DASH DASH)][(NUMERAL 1)][(NOUN sUM)][(DOT DOT)]
[(VERB zwriM)][(PREPOSITION yl)][(NOUN-DEF hprwswt)][(NOUN mlx)][(PREFIX w)(NOUN mnixiM)][(PREFIX b)	(NOUN-CONST cd)][(PREFIX l)	(NUMERAL xci)][(NOUN eyh)][(DOT DOT)]
[(VERB mngbiM)][(PREPOSITION at)][(NOUN-DEF hxciliM)][(VERB-INF mhmlx)][(PREFIX w)	(PREFIX m)(NOUN-DEF hnwzliM)][(PREFIX e)(VERB hpriew)][(DOT DOT)]
[(VERB mxmmiM)][(NOUN emN)][(PROPERNAME bgwh)][(PREFIX k)(NOUN-CONST xci)][(NOUN sUM)][(PREFIX b)(NOUN mxbt)][(ADJECTIVE gdwlh)][(CM CM)][(VERB mwsipiM)][(PREPOSITION at)][(NOUN-DEF hxciliM)][(LRB LRB)][(PREFIX b)	(QUANTIFIER kmh)][(NOUN pymiM)][(RRB RRB)][(PREFIX w)(VERB mvgniM)][(PREPOSITION yd)][(PREFIX e)	(PRONOUN hM)][(VERB mzhibiM)][(PREFIX m)	(NUMERAL eni)][(NOUN-DEF hcddiM)][(DOT DOT)]
[(NOUN-DEF hxciliM)][(VERB swpgiM)][(QUANTIFIER hrbh)][(NOUN emN)][(PREFIX b)	(NOUN-CONST mhlK)][(NOUN-DEF hvigwN)][(PREFIX w)	(CONJUNCTION lkN)][(MODAL ie)][(VERB-INF lhwsiP)][(PREFIX l)(NOUN-CONST mxbt)][(QUANTIFIER mdi)][(NOUN pyM)][(ADJECTIVE emN)][(DOT DOT)]
[(PARTICIPLE mwciaiM)][(PREFIX w)(NOUN mspigiM)][(PREPOSITION yl)][(NOUN-CONST mgbt)][(NOUN niir)][(DOT DOT)]
[(VERB mxmmiM)][(QUANTIFIER ywd)][(NOUN emN)][(PREFIX b)(NOUN mxbt)][(ADJECTIVE nqiih)][(PREFIX w)(VERB mwsipiM)][(PREPOSITION at)][(NOUN-CONST plxi)][(NOUN-DEF hygbniwt)][(DOT DOT)]
[(VERB kwteiM)][(PREPOSITION at)][(NOUN-POSSESSIVE eini)][(NOUN-DEF hewM)][(PREPOSITION myl)][(NOUN-DEF hygbniwt)][(PREFIX w)(VERB mvgniM)][(PREPOSITION yl)][(NOUN lhbh)][(ADJECTIVE gbwhh)][(NUMERAL xme)][(NOUN dqwt)][(DOT DOT)]
[(NOUN msdriM)][(PREPOSITION at)][(NOUN prwswt)][(NOUN-DEF hxciliM)][(PREFIX b)(NOUN-DEF ekbh)][(PREFIX b)	(NOUN-CONST txtit)][(NOUN-CONST kli)][(NOUN-DEF hhgeh)][(DOT DOT)]
[(VERB msdriM)][(PREPOSITION mylihN)][(PREPOSITION at)][(NOUN-DEF hygbniwt)][(PREFIX w)(NOUN-DEF hewM)][(DOT DOT)]
[(VERB pwrsiM)][(PREPOSITION at)][(NOUN-DEF hplpliM)][(PREFIX w)(VERB msdriM)][(PREPOSITION yl)][(NOUN-DEF hygbniwt)][(DOT DOT)]
[(NOUN mgieiM)][(ADJECTIVE xM)][(CONJUNCTION aw)][(PREFIX b)(NOUN-CONST vmprvwrt)][(NOUN-DEF hxdr)][(CM CM)][(ADVERB hki)][(ADJECTIVE vyiM)][(PREPOSITION yM)][(VERB xlh)][(PROPERNAME vriih)][(DOT DOT)]
EOF
