[(NUMBEREXPRESSION 1.)][(VERB pwrsiM)][(PREPOSITION at)][(NOUN-DEF hxciliM)][(PREFIX l)	(NOUN prwswt)][(PREFIX b)	(NOUN-DEF ywbi)][(NOUN sUM)][(PREFIX l)	(NOUN-CONST awrK)][(CONJUNCTION aw)][(PREFIX l)	(NOUN-CONST rwxb)][(LRB LRB)][(PREPOSITION lpi)][(NOUN-POSSESSIVE vymkM)][(RRB RRB)][(CM CM)][(VERB mmlixiM)][(ADVERB hivb)][(PREFIX w)(NOUN mnixiM)][(PREFIX k)(NOUN-POSSESSIVE xci)][(VERB eyh)][(VERB-INF lhgir)][(NOUN nwzliM)][(DOT DOT)]
[(PREPOSITION axri)][(NUMERAL xci)][(NOUN eyh)][(VERB miibeiM)][(ADVERB hivb)][(PREPOSITION at)][(NOUN prwswt)][(NOUN-DEF hxciliM)][(PREPOSITION yM)][(NOUN niir)][(ADJECTIVE swpg)][(DOT DOT)]
[(NUMBEREXPRESSION 2.)][(VERB mxmmiM)][(ADVERB hivb)][(QUANTIFIER myv)][(NOUN emN)][(PREFIX b)(NOUN mxbt)][(ADJECTIVE gdwlh)][(PREFIX w)(ADJECTIVE evwxh)][(CM CM)][(VERB mknisiM)][(NOUN-CONST prwst)][(NOUN-CONST gzr)][(NUMERAL axt)][(CONJUNCTION kdi)][(PREFIX e)(NOUN-DEF hemN)][(NEGATION la)][(VERB ierP)][(LRB LRB)][(QUANTIFIER kl)][(NOUN pyM)][(PREFIX e)(NOUN-CONST prwst)][(NOUN-DEF hgzr)][(VERB nerpt)][(CM CM)][(VERB mxlipiM)][(PREPOSITION awth)][(PREFIX b)(ADJECTIVE axrt)][(CM CM)][(NOUN-CONST vriq)][(NOUN-POSSESSIVE pccti)][(RRB RRB)][(NUMBEREXPRESSION 3.)][(VERB mvgniM)][(PREPOSITION at)][(NOUN-DEF hxciliM)][(PREPOSITION yd)][(PREFIX e)(VERB meximiM)][(ADVERB hivb)][(PREFIX m)	(NUMERAL eni)][(NOUN-DEF hcddiM)][(PREFIX w)(VERB mybiriM)][(PREFIX l)(NOUN cinwN)][(PREFIX b)	(NOUN-DEF clxt)][(PREPOSITION yM)][(NOUN niir)][(ADJECTIVE swpg)][(DOT DOT)]
[(NUMBEREXPRESSION 4.)][(PREFIX b)(NOUN qyrh)][(ADJECTIVE myrbbiM)][(PREPOSITION at)][(QUANTIFIER kl)][(NOUN-CONST xwmri)][(NOUN-DEF hrwvb)][(CM CM)][(NOUN nwzliM)][(ADVERB txilh)][(DOT DOT)]
[(NUMBEREXPRESSION 5.)][(VERB msdriM)][(PREFIX b)(NOUN-CONST qwpst)][(NOUN plsviq)][(NOUN ekbh)][(PREPOSITION el)][(NOUN xciliM)][(CM CM)][(PREFIX w)(PREPOSITION mylih)][(QUANTIFIER myv)][(PREFIX m)(NOUN-DEF hrwvb)][(CM CM)][(ADVERB ewb)][(NOUN xciliM)][(PREFIX w)	(ADVERB ewb)][(NOUN rwvb)][(PREFIX w)(VERB msiimiM)][(ADVERB kmwbN)][(PREFIX b)(NOUN-DEF rwvb)][(DOT DOT)]
[(NUMBEREXPRESSION 6.)][(NOUN mksiM)][(PREFIX w)(NOUN mknisiM)][(PREFIX l)(NOUN mqrr)][(PREFIX l)(NOUN-CONST spigt)][(NOUN vymiM)][(PREPOSITION bmeK)][(PREFIX k)	(NOUN eyh)][(DOT DOT)]
</paragraph>
[(MODAL aper)][(VERB-INF lhgie)][(PREFIX k)(NOUN-DEF slv)][(CM CM)][(MODAL aper)][(VERB-INF lakwl)][(PREPOSITION yM)][(QUANTIFIER hrbh)][(VERB xlh)][(CM CM)][(MODAL aper)][(VERB-INF lakwl)][(PREPOSITION yl)][(NOUN vwsv)][(PREPOSITION yM)][(NOUN lbnh)][(CM CM)][(NEGATION la)][(VERB menh)][(INTERROGATIVE aiK)][(CM CM)][(VERB hvyM)][(NOUN mdhiM)][(CM CM)][(PREPOSITION aclnw)][(PRONOUN zh)][(VERB ngmr)][(PREPOSITION twK)][(NOUN iwmiiM)][(DOT DOT)]
</paragraph>
[(NOUN giwwN)][(CLN CLN)][(MODAL aper)][(PREPOSITION bmqwM)][(NOUN xciliM)][(VERB-INF lhetme)][(PREFIX b)(NOUN plpliM)][(PREFIX e)(VERB nqlw)][(PREFIX b)(NOUN gril)][(PREFIX w)(NOUN-POSSESSIVE qwlpw)][(DOT DOT)]
EOF
