[(VERB mxmmiM)][(PREPOSITION at)][(NOUN-DEF hemN)][(VERB-INF bsir)][(ADJECTIVE qvN)][(CM CM)][(VERB mwsipiM)][(PREPOSITION at)][(NOUN-CONST abqt)][(PROPERNAME hqari)][(PREFIX w)(VERB mbeliM)][(PREPOSITION yl)][(NOUN ae)][(ADJECTIVE nmwkh)][(PREPOSITION twK)][(NOUN bxieh)][(PROPERNAME k2)][(DASH DASH)][(NOUN dqwt)][(DOT DOT)]
[(VERB mwsipiM)][(PREPOSITION at)][(NOUN miC)][(ADJECTIVE-DEF hygbniwt)][(PREFIX w)(NOUN mbeliM)][(PREPOSITION yl)][(NOUN ae)][(ADJECTIVE binwnit)][(PROPERNAME k5)][(DASH DASH)][(NOUN dqwt)][(CONJUNCTION aw)][(PREPOSITION yd)][(PREFIX e)(VERB neart)][(ADVERB rq)][(NOUN-CONST mxcit)][(NOUN-CONST mnpx)][(NOUN-DEF hmiC)][(CM CM)][(VERB mnixiM)][(VERB-INF lhtqrr)][(DOT DOT)]
</paragraph>
[(NOUN myrbbiM)][(PREPOSITION at)][(NOUN tyrwbt)][(NOUN miC)][(ADJECTIVE-DEF hygbniwt)][(PREPOSITION yM)][(PROPERNAME hmiwnit)][(CM CM)][(VERB vwymiM)][(CONJUNCTION kdi)][(VERB-INF ltqN)][(PREPOSITION at)][(NOUN-DEF htibwl)][(PREFIX w)(VERB mwsipiM)][(ADVERB ywd)][(NOUN-CONST abqt)][(PROPERNAME qari)][(CONJUNCTION aM)][(EXISTENTIAL ie)][(NOUN cwrK)][(DOT DOT)]
[(PREPOSITION at)][(NOUN-DEF hrwvb)][(MODAL aper)][(VERB-INF lhkiN)][(NOUN iwM)][(ADVERB mrae)][(PREFIX w)	(VERB-INF lemwr)][(PREFIX b)	(NOUN kli)][(ADJECTIVE sgwr)][(PREFIX b)(NOUN-DEF mqrr)][(DOT DOT)]
[(VERB ywrkiM)][(PREPOSITION at)][(NOUN-CONST yli)][(NOUN-DEF hxsh)][(PREPOSITION yl)][(NOUN mge)][(CM CM)][(VERB xwciM)][(PREPOSITION at)][(NOUN-DEF hbiciM)][(PREFIX l)	(NOUN-CONST awrK)][(PREFIX w)(VERB emiM)][(PREPOSITION awtN)][(PREFIX b)	(NOUN-CONST mrkz)][(NOUN-DEF hmge)][(PREFIX ke)(NOUN-DEF hcd)][(ADJECTIVE-DEF hxtwK)][(PREPOSITION klpi)][(PROPERNAME mvy)][(PREFIX w)(NOUN-DEF hxlq)][(ADJECTIVE-DEF hcr)][(PREPOSITION el)][(NOUN-DEF hbich)][(VERB pwnh)][(PREFIX l)	(NOUN-CONST mrkz)][(CM CM)][(PREFIX b)	(NOUN-CONST yzrt)][(NOUN-CONST kP)][(NOUN mksiM)][(QUANTIFIER kl)][(NOUN bich)][(PREFIX b)(NOUN-CONST ekbt)][(NOUN-CONST rwvb)][(PROPERNAME qari)][(DOT DOT)]
</paragraph>
[(NOUN mnixiM)][(PREPOSITION yli)][(NOUN pvrwzilih)][(PREPOSITION yl)][(QUANTIFIER kl)][(NUMERAL axt)][(DOT DOT)]
[(VERB vwpxiM)][(PREPOSITION yM)][(NOUN-DEF hmge)][(NOUN qlwt)][(PREPOSITION yl)][(NOUN-DEF hewlxN)][(PREPOSITION yl)][(MWE mnt)][(PREFIX e)(NOUN-CONST ekbt)][(PROPERNAME hmiwnit)][(COPULA thih)][(ADVERB iwtr)][(ADJECTIVE axidh)][(PREFIX w)(ADJECTIVE dqh)][(CM CM)][(VERB mgieiM)][(PREPOSITION at)][(QUANTIFIER ear)][(NOUN-DEF hrwvb)][(PREFIX b)	(NOUN kli)][(ADJECTIVE nprd)][(DOT DOT)]
EOF
