[(DOT DOT)]
[(PREPOSITION at)][(NOUN-CONST avriwt)][(NOUN-DEF hawrz)][(VERB meriM)][(PREFIX b)	(NOUN-DEF miM)][(ADJECTIVE xmiM)][(PREFIX l)(NOUN-DEF rikwK)][(CM CM)][(VERB msnniM)][(PREFIX w)(NOUN mqrriM)][(PREFIX b)	(NOUN-DEF miM)][(DOT DOT)]
[(NOUN xwtkiM)][(PROPERNAME gs.)][(NUMBEREXPRESSION 2.)][(VERB xwciM)][(PREPOSITION at)][(NOUN-CONST pvriwt)][(PROPERNAME hpwrvwblw)][(PREFIX w)(NOUN xwtkiM)][(PREFIX l)	(NOUN prwswt)][(NOUN gswt)][(DOT DOT)]
[(VERB xwciM)][(CONJUNCTION gM)][(PREPOSITION at)][(NOUN-CONST pvriwt)][(PROPERNAME hempiniwN)][(DOT DOT)]
[(NUMBEREXPRESSION 3.)][(VERB pwrsiM)][(PREPOSITION at)][(NOUN-DEF hewM)][(PREFIX w)	(PREPOSITION at)][(NOUN-DEF hkrieh)][(PREFIX l)(NOUN yigwliM)][(ADJECTIVE dqiM)][(DOT DOT)]
[(VERB xwciM)][(PREPOSITION at)][(NOUN-DEF hyrmwniM)][(ADJECTIVE-DEF hlxiM)][(PREPOSITION yM)][(NOUN skiN)][(ADJECTIVE xdh)][(DOT DOT)]
[(NUMBEREXPRESSION 4.)][(VERB mxmmiM)][(NOUN-CONST mxbt)][(NOUN vplwN)][(PREPOSITION lla)][(NOUN ewmN)][(PREFIX w)(VERB mwsipiM)][(PREPOSITION at)][(NOUN-DEF hcnwbriM)][(DOT DOT)]
[(NOUN qwliM)][(PREPOSITION twK)][(NOUN hqpch)][(PREPOSITION lla)][(NOUN hpsqh)][(PREPOSITION yd)][(PREFIX e)(NOUN-DEF hcnwbriM)][(VERB mtxiliM)][(VERB-INF lhiqlwt)][(PREFIX w)(VERB-INF lhexiM)][(ADVERB myv)][(DOT DOT)]
[(PARTICIPLE mwciaiM)][(PREFIX l)(NOUN clxt)][(ADJECTIVE rxbh)][(PREFIX l)(NOUN-DEF cinwN)][(DOT DOT)]
[(NUMBEREXPRESSION 5.)][(VERB mxmmiM)][(PREFIX b)(NOUN mxbt)][(ADJECTIVE rxbh)][(NUMERAL 2)][(NOUN-CONST kpwt)][(NOUN emN)][(NOUN zit)][(PREFIX w)(VERB mwsipiM)][(PREPOSITION at)][(NOUN-DEF hkrieh)][(CM CM)][(NOUN-CONST ynpi)][(NOUN-DEF hvimiN)][(ADJECTIVE-DEF helmiM)][(PREFIX w)(NOUN-DEF hewM)][(PREFIX w)(VERB mqpiciM)][(PREFIX k)(NOUN-CONST xci)][(NOUN dqh)][(DOT DOT)]
[(NUMBEREXPRESSION 6.)][(VERB mwsipiM)][(PREPOSITION at)][(NOUN-DEF hpvriwt)][(PREFIX w)(VERB mqpiciM)][(PREFIX l)][(DASH DASH)][(NUMERAL 3)][(NOUN dqwt)][(DOT DOT)]
[(VERB mwsipiM)][(NUMERAL 1/4)][(NOUN-CONST kws)][(NOUN iiN)][(ADJECTIVE adwM)][(PREFIX w)(VERB myrbbiM)][(PREPOSITION yd)][(PREFIX l)	(NOUN-CONST cmcwM)][(QUANTIFIER rwb)][(NOUN-DEF hnwzliM)][(CM CM)][(PREFIX k)][(DASH DASH)][(NUMERAL 2)][(DASH DASH)][(NUMERAL 4)][(NOUN dqwt)][(ADVERB lyrK)][(DOT DOT)]
[(ADJECTIVE xewb)][(NEGATION la)][(VERB-INF lclwt)][(ADVERB iwtr)][(PREFIX m)	(NOUN-CONST idi)][(PROPERNAME kK)][(PREFIX e)(NOUN-DEF hpvriwt)][(VERB iemrw)][(PREPOSITION yl)][(NOUN-POSSESSIVE cwrtN)][(DOT DOT)]
[(NUMBEREXPRESSION 7.)][(NOUN mcnniM)][(DOT DOT)]
[(VERB mtbliM)][(PREFIX b)(NOUN mlx)][(PREFIX w)	(QUANTIFIER myv)][(NOUN plpl)][(ADJECTIVE lbN)][(CM CM)][(NOUN-DEF hemir)][(VERB qcwC)][(CM CM)][(NOUN-DEF hyrmwniM)][(CM CM)][(NOUN-CONST kP)][(NOUN emN)][(NOUN zit)][(PREFIX w)(NOUN-CONST xwmC)][(NOUN-CONST bN)][(NOUN iiN)][(ADJECTIVE adwM)][(DOT DOT)]
[(VERB mwsipiM)][(PREPOSITION at)][(NOUN-CONST avriwt)][(NOUN-DEF hawrz)][(PREFIX w)(NOUN myrbbiM)][(DOT DOT)]
[(NUMBEREXPRESSION 8.)][(NOUN mqrriM)][(PREFIX l)	(NOUN eyh)][(PREFIX b)(NOUN mqrr)][(DOT DOT)]
[(PREPOSITION lpni)][(NOUN-DEF hhgeh)][(VERB mpzriM)][(NOUN cnwbriM)][(PREPOSITION myl)][(NOUN-DEF hpvriwt)][(DOT DOT)]
EOF
