[(NOUN awpN)][(NOUN-DEF hhknh)][(CLN CLN)]
</paragraph>
[(NUMBEREXPRESSION 1.)][(VERB mxmmiM)][(PREPOSITION at)][(NOUN-DEF htnwr)][(PREFIX l)(NOUN xwM)][(ADJECTIVE gbwh)][(LRB LRB)][(NUMERAL 220)][(NOUN mylwt)][(RRB RRB)][(DOT DOT)]
[(VERB qwlpiM)][(PREPOSITION at)][(NOUN-DEF hagsiM)][(DOT DOT)]
[(VERB mnixiM)][(QUANTIFIER kl)][(NOUN ags)][(PREPOSITION yl)][(NOUN-CONST iriyt)][(NOUN alwminiwM)][(PREFIX w)(VERB mrimiM)][(ADVERB qct)][(PREPOSITION at)][(NOUN-CONST ewli)][(NOUN-DEF hiriyh)][(DOT DOT)]
[(VERB mzlipiM)][(PREPOSITION yl)][(NOUN-DEF hags)][(ADJECTIVE emN)][(NOUN zit)][(PREFIX w)(VERB zwriM)][(NOUN plpl)][(ADJECTIVE exwr)][(DOT DOT)]
[(VERB swgriM)][(PREPOSITION at)][(NOUN-DEF hniir)][(PREPOSITION myl)][(NOUN-DEF hags)][(PRONOUN kK)][(PREFIX e)(VERB tiwwcr)][(NOUN yviph)][(DOT DOT)]
[(NOUN cwliM)][(NUMERAL 30)][(NOUN dqwt)][(CM CM)][(PARTICIPLE mwciaiM)][(PREFIX m)(NOUN-DEF htnwr)][(PREFIX w)(VERB meairiM)][(PREPOSITION at)][(NOUN-DEF hyviph)][(ADJECTIVE sgwrh)][(ADVERB ywd)][(NUMERAL 30)][(NOUN dqwt)][(DOT DOT)]
[(NUMBEREXPRESSION 2.)][(VERB pwtxiM)][(PREPOSITION at)][(NOUN-DEF hyvipwt)][(PREPOSITION myl)][(NOUN qyrit)][(PREFIX w)(VERB mybiriM)][(PREPOSITION alih)][(PREPOSITION at)][(NOUN-DEF hnwzliM)][(PREFIX e)	(VERB hcvbrw)][(DOT DOT)]
[(VERB xwciM)][(PREPOSITION at)][(NOUN-DEF hagsiM)][(PREFIX l)(NOUN-POSSESSIVE awrkM)][(PREFIX w)(PREPOSITION byzrt)][(NOUN kpit)][(VERB mslqiM)][(PREPOSITION at)][(NOUN-DEF hlibh)][(DOT DOT)]
[(VERB mnixiM)][(PREFIX b)(NOUN-DEF qyrh)][(DOT DOT)]
[(NUMBEREXPRESSION 3.)][(VERB mwsipiM)][(PREFIX l)(NOUN-DEF qyrh)][(PREPOSITION at)][(NOUN-DEF hyliM)][(CM CM)][(NOUN-DEF hagwziM)][(CM CM)][(NOUN-CONST earit)][(NOUN emN)][(NOUN-DEF hzit)][(CM CM)][(NOUN miC)][(NOUN-DEF hlimwN)][(CM CM)][(NOUN-DEF hewM)][(PREFIX w)(VERB hmlx)][(PREFIX w)(NOUN myrbbiM)][(PREFIX b)	(NOUN zhirwt)][(DOT DOT)]
[(PREFIX m)	(NOUN xlqiM)][(PREPOSITION at)][(NOUN-DEF hslv)][(PREFIX l)(NOUN clxwt)][(ADJECTIVE aieiwt)][(LRB LRB)][(CONJUNCTION aw)][(VERB mybiriM)][(PREFIX l)(NOUN-CONST qyrt)][(NOUN hgeh)][(RRB RRB)][(DOT DOT)]
[(VERB mnixiM)][(PREPOSITION at)][(NOUN-DEF hgbinh)][(ADVERB mlmylh)][(PREFIX w)(NOUN mgieiM)][(DOT DOT)]
EOF
